# Generated by Django 3.1.7 on 2021-04-01 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doc',
            name='address',
        ),
        migrations.RemoveField(
            model_name='doc',
            name='certification_date',
        ),
        migrations.RemoveField(
            model_name='doc',
            name='city',
        ),
        migrations.RemoveField(
            model_name='doc',
            name='country',
        ),
        migrations.RemoveField(
            model_name='doc',
            name='entity_code',
        ),
        migrations.RemoveField(
            model_name='doc',
            name='enumeration_date',
        ),
        migrations.RemoveField(
            model_name='doc',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='doc',
            name='gender',
        ),
        migrations.RemoveField(
            model_name='doc',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='doc',
            name='mail_address',
        ),
        migrations.RemoveField(
            model_name='doc',
            name='mail_city',
        ),
        migrations.RemoveField(
            model_name='doc',
            name='mail_country',
        ),
        migrations.RemoveField(
            model_name='doc',
            name='mail_postal_code',
        ),
        migrations.RemoveField(
            model_name='doc',
            name='mail_state',
        ),
        migrations.RemoveField(
            model_name='doc',
            name='organization',
        ),
        migrations.RemoveField(
            model_name='doc',
            name='postal_code',
        ),
        migrations.RemoveField(
            model_name='doc',
            name='sole_proprietor',
        ),
        migrations.RemoveField(
            model_name='doc',
            name='state',
        ),
        migrations.RemoveField(
            model_name='doc',
            name='tax_code',
        ),
        migrations.RemoveField(
            model_name='doc',
            name='tax_defintion',
        ),
        migrations.RemoveField(
            model_name='doc',
            name='tax_group',
        ),
        migrations.RemoveField(
            model_name='doc',
            name='tax_name',
        ),
        migrations.RemoveField(
            model_name='doc',
            name='telephone_number',
        ),
        migrations.AlterField(
            model_name='doc',
            name='npi',
            field=models.CharField(default='', max_length=10),
        ),
    ]
